# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('src_mac', models.CharField(max_length=17)),
                ('first_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connections',
            },
        ),
    ]
